import prisma from '../../config/prisma';
import { generateObject } from 'ai';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { z } from 'zod';

const google = createGoogleGenerativeAI({
  apiKey: process.env.GEMINI_API_KEY || ''
});

export const insightEngineService = {
  /**
   * Generates natural language insights (Recommendations) by analyzing 
   * the statistical Forecasts vs Current Inventory Levels.
   */
  async generateBusinessInsights(businessId: string) {
    console.log(`Gathering data for AI Insights on Business: ${businessId}`);

    // 1. Get current inventory stock levels using our append-only ledger
    const inventoryMap = await prisma.inventoryMovement.groupBy({
      by: ['productId'],
      where: { businessId: businessId },
      _sum: { quantityDelta: true }
    });

    const products = await prisma.product.findMany({
      where: { businessId, isActive: true },
      include: {
        productSupplierPrices: {
          where: { isPreferred: true }
        } // For lead time and cost
      }
    });

    // 2. Get the latest forecasts generated by Python/Prophet
    // We only want the most recently generated forecast per product
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const recentForecasts = await prisma.forecast.findMany({
      where: {
        businessId,
        generatedAt: { gte: thirtyDaysAgo }
      },
      orderBy: { generatedAt: 'desc' },
      distinct: ['productId']
    });

    // 3. Build the Data Context string for the LLM
    const businessMetrics: any[] = [];

    for (const product of products) {
      const stock = inventoryMap.find(m => m.productId === product.id)?._sum.quantityDelta?.toNumber() || 0;
      const forecast = recentForecasts.find(f => f.productId === product.id);
      
      const supplierCost = product.productSupplierPrices[0]?.unitCost?.toNumber() || product.costPrice.toNumber();
      const leadTime = product.productSupplierPrices[0]?.leadTimeDays || 7;
      
      let status = "Unknown";
      let daysOfSupply = "Unknown";
      let urgency = "low";

      if (forecast && forecast.predictedDemand.toNumber() > 0) {
        // Daily run rate = (Total 30-day Demand) / 30
        const dailyBurnRate = forecast.predictedDemand.toNumber() / 30;
        const dos = stock / dailyBurnRate;
        daysOfSupply = `${dos.toFixed(1)} days`;

        if (dos < leadTime) {
          status = "Critical Stockout Risk";
          urgency = "high";
        } else if (dos > 90) {
          status = "Severe Overstock (Capital Trapped)";
          urgency = "medium";
        } else {
          status = "Healthy";
        }
      } else {
         if (stock > 0) {
           status = "Dead Stock - No forecasted demand";
           urgency = "medium";
         }
      }

      businessMetrics.push({
        id: product.id,
        name: product.name,
        currentStock: stock,
        reorderPoint: product.reorderPoint,
        forecasted30DayDemand: forecast ? forecast.predictedDemand.toNumber().toFixed(0) : "0",
        supplierLeadTimeDays: leadTime,
        margin: `${((product.sellingPrice.toNumber() - supplierCost) / product.sellingPrice.toNumber() * 100).toFixed(1)}%`,
        status,
        urgency
      });
    }

    // Filter out "healthy" ones to save LLM tokens and focus on problems
    const actionableMetrics = businessMetrics.filter(m => m.urgency !== 'low');

    if (actionableMetrics.length === 0) {
      return { message: "No actionable insights found. Business is healthy." };
    }

    // 4. Pass Data to Vercel AI SDK to generate Human-Readable Recommendations
    const promptContext = JSON.stringify(actionableMetrics, null, 2);
    
    console.log("Asking Gemini 1.5 Pro for Insights formulation...");

    const { object } = await generateObject({
      model: google('gemini-1.5-pro-latest'), // Use a stable model string
      schema: z.object({
        recommendations: z.array(z.object({
          productId: z.string().uuid(),
          title: z.string(),
          body: z.string().describe("Human readable explanation of what to do and why, using the stats."),
          recommendationType: z.enum(['restock', 'reduce_order', 'promote', 'discontinue', 'pricing_adjustment']),
          priority: z.enum(['high', 'medium', 'low']),
          suggestedQuantity: z.number().optional().describe("If restocking, exact number to order based on demand and lead time")
        }))
      }) as any, // Explicitly cast to 'any' to bypass TS2589 infinite recursion
      prompt: `Analyze these inventory metrics: ${promptContext}. Create actionable business recommendations.`
    });

    // Fix TypeScript 'unknown' error by casting
    const result = object as any;
    
    // 5. Store Recommendations in Database & Return
    const recommendations = await Promise.all(
      result.recommendations.map(async (rec: any) => {
        return prisma.recommendation.create({
          data: {
            businessId,
            productId: rec.productId,
            recommendationType: rec.recommendationType as any,
            title: rec.title,
            body: rec.body,
            priority: rec.priority as any,
            suggestedQuantity: rec.suggestedQuantity,
            status: 'pending' // pending review by owner
          }
        });
      })
    );

    console.log(`Saved ${recommendations.length} new AI recommendations to database.`);
    return { recommendations };
  }
};
